volumes:
  etc_wireguard:

services:
  clearnet-node:
    environment:
      # Change Language:
      # (Supports: en, ua, ru, tr, no, pl, fr, de, ca, es, ko, vi, nl, is, pt, chs, cht, it, th, hi, ja)
      - LANG=en
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=localhost

      # Optional:
      # - PASSWORD_HASH=
      # (needs double $$, hash of 'foobar123'; see "How_to_generate_an_bcrypt_hash.md" for generate the hash)
      - PORT=8081
      - WG_PORT=51820
      # - WG_CONFIG_PORT=92820
      - WG_DEFAULT_ADDRESS=10.8.0.x
      - WG_DEFAULT_DNS=1.1.1.1,8.8.8.8
      # - WG_MTU=1420
      - WG_ALLOWED_IPS=0.0.0.0/0
      # - WG_PERSISTENT_KEEPALIVE=25
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      # - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt
      - UI_TRAFFIC_STATS=true
      - UI_CHART_TYPE=1 # (0 Charts disabled, 1 # Line chart, 2 # Area chart, 3 # Bar chart)
      # - WG_ENABLE_ONE_TIME_LINKS=true
      # - UI_ENABLE_SORT_CLIENTS=true
      # - WG_ENABLE_EXPIRES_TIME=true
      # - ENABLE_PROMETHEUS_METRICS=false
      # - PROMETHEUS_METRICS_PASSWORD=$$2a$$12$$vkvKpeEAHD78gasyawIod.1leBMKg8sBwKW.pQyNsq78bXV3INf2G # (needs double $$, hash of 'prometheus_password'; see "How_to_generate_an_bcrypt_hash.md" for generate th>
      # CLEARNET Environment Variables
      - WALLET_PRIVATE_KEY=f0ce4f9c5521bfb662312a18794928ba3c24ac8afa55c4687d894452818faaeb
      - INFURA_ENDPOINT=https://sepolia.infura.io/v3/8c1eb7cd8a5a43c9bc5c3d69db182b83
      - CHAIN_ID=11155111
      - CLEARNET_CONTRACT_ADDRESS=0x0305e95225f65db13e98c775dbb95b98178ae73b
      - CLRTOKEN_CONTRACT_ADDRESS=0xf1664c17887767c8f58695846babb349ca61d2e9
      - PROXY_PORT=8080
      #- VPN_PORT=51826

    image: jlucfust/clearnet-node
    container_name: clearnet-node
    volumes:
      - ./etc_wireguard:/etc/wireguard
    ports:
      - "8080:8080/tcp"
      - "51820:51820/udp"
      - "8081:8081/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      # - NET_RAW # ⚠️ Uncomment if using Podman
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
